name: "CI"

on:
  pull_request:
  push:
    branches:
      - main 

jobs:

  build:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macOS-latest

    runs-on: ${{ matrix.platform }}

    steps:

    - name: Checking out the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup
      uses: ./.github/actions/common-setup
      with:
        CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    - name: Flake check
      run: |
        nix flake check --show-trace -L
