name: "Build"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checking out the repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Installing Nix
      uses: cachix/install-nix-action@v10
    - name: Use Cachix
      uses: cachix/cachix-action@v6
      with:
        name: asciinema-scenario
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: Build
      run: |
        nix-build
